### ISSUE TITLE
第四版的英文版电子书在哪里购买？

### ISSUE THREAD

**Issue by Jancat** [Jack-Sparrow/CSS-The-Definitive-Guide-4th-zh-CN#1]
你提供的地址里只找到第三版，第四版没找到？谢谢告知
CSS: The Definitive Guide 
by Eric A. Meyer
**Third** Edition November 2006 
Print: $44.99
Ebook: $35.99

**Comment by Jack-Sparrow** [comment]
@Jancat 第四版是分开的，每一章是一本书

**Comment by Jancat** [comment]
@Jack-Sparrow 请问我在哪里可以找到这些章节的英文原文地址？

**Comment by jkvim** [comment]
@Jancat amazon

**Comment by Jancat** [comment]
@jkvim 还没开售

**Comment by vincentyahaha** [comment]
虽然本书还没开售但是可以在 o'reilly Safari 购买subscription， 阅读pre-released内容。
可以邮箱先注册10天试用期试试。

**Comment by Jack-Sparrow** [comment]
http://shop.oreilly.com/product/0636920012726.do
