### ISSUE TITLE
文中有处文字错误需要修改下

### ISSUE THREAD

**Issue by qiaosin** [Jack-Sparrow/CSS-The-Definitive-Guide-4th-zh-CN#2]
多类选择器下的以下文字：
_**IE7以前的Internet Exlorer版本处理多类选择器有问题。在这些旧版本中，虽然可以选择列表中的单个类名，但对多个类名的选择无法正常生效。`p.warning`会按照预期生效，但` p.warning.help`会匹配任意一个`class`属性值列表中含有`help`的`p`元素。如果你使用`p.warning.help`，旧版本的IE会匹配任何一个`class`值列表中含有`warning`的`p`元素，而无论值中有没有`help`。**_
应该调整为：
_**IE7以前的Internet Exlorer版本处理多类选择器有问题。在这些旧版本中，虽然可以选择列表中的单个类名，但对多个类名的选择无法正常生效。`p.warning`会按照预期生效，但` p.warning.help`会匹配任意一个`class`属性值列表中含有`help`的`p`元素。如果你使用`p.help.warning`，旧版本的IE会匹配任何一个`class`值列表中含有`warning`的`p`元素，而无论值中有没有`help`。**_
即：`p.warning.help` 写错了，顺序要换成：`p.help.warning`

**Comment by Jack-Sparrow** [comment]
看了一下原文，这段内容已经被删掉了。最初翻译是依据该章节较早的一个版本，正式版本里面移除了这段。感谢！
