### ISSUE TITLE
讨论一下关于第一章前言中 chrome 一词的意思

### ISSUE THREAD

**Issue by 57f4b3da** [Jack-Sparrow/CSS-The-Definitive-Guide-4th-zh-CN#3]
### 原文:
```text
Gecko-based browsers use CSS to affect the presentation of the browser **chrome** itself
```

其中 chrome 一词指的是浏览器 viewport 之外的部分, 比如地址栏, 书签栏, 标签栏等部分, 而不是指 Google Chrome 浏览器

我认为这里应翻译成 **通过 CSS 影响浏览器自身 chrome 的呈现**, 最好能再加上关于 Chrome 一词的译注

### Chrome 定义:

**Definition**: Chrome is the visual design elements that give users information about or commands to operate on the screen's content (as opposed to being part of that content). These design elements are provided by the underlying system — whether it be an operating system, a website, or an application — and surround the user's data.

参考资料: 

[Browser and GUI Chrome](https://www.nngroup.com/articles/browser-and-gui-chrome/)
[StackOverflow: What does 'chrome' mean?](https://stackoverflow.com/questions/5071905/what-does-chrome-mean)

**Comment by Jack-Sparrow** [comment]
感谢指出，已经修复
